### ISSUE TITLE
Error when using the addon with Vite

### ISSUE THREAD

**Issue by ladislas14** [reme3d2y/storybook-addon-live-examples#1]
Hi,

I'm asking myself to switch from Styleguidist to Storybook to use Vite as builder (it's really faster than Webpack).

So I want to use your addon to retrieve the live edit from Styleguidist, but I'm facing some issues. I managed to have Storybook running by adding `react-live` to the list of `optimizeDeps.include`, but now I get the following error in the code editing part :

![Capture d’écran 2021-09-02 183718](https://user-images.githubusercontent.com/1148173/131883046-d44c94eb-6e8b-4572-9128-1182a2885c0d.png)

Do you have any idea about why i Get this issue ?

**Comment by reme3d2y** [comment]
@ladislas14 hi ✋ 

Can you show me an example of the code you want to display?
You probably need to wrap your code in `render(() => /* your example here */)`

**this works as is**
```tsx
<Button>Click</Button>
```

**this code should be wrapped inside render**
```tsx
render(() => {
    const text = 'Click';

    return (
        <Button>{text}</Button>
    )
})
```

You can see code samples [here](https://github.com/reme3d2y/storybook-addon-live-examples/tree/main/stories)

**Comment by ladislas14** [comment]
Hi,

I just used your examples.

I pushed my code in a repo so you can check it and test it yourself : https://github.com/ladislas14/storybook-vite

Thanks :)

**Comment by reme3d2y** [comment]
I tried leaving only addon-docs and for some reason it does not display the source code. This is a necessary condition for the storybook-addon-live-example

I'll try to fix it and reply later

![image](https://user-images.githubusercontent.com/9968618/131977542-edb4d90f-e911-4e5a-a593-0dfcdfcf8c57.png)

**Comment by reme3d2y** [comment]
storybook-addon-live-example works as expected in mdx, so you can use this format.

But something wrong with addon-docs and storybook-builder-vite
https://github.com/eirslett/storybook-builder-vite/issues/44

**Comment by ladislas14** [comment]
Thank you ! I tried with MDX files and yes it works ! 

I will keep an eye on the other issue hoping that it will work with CSF files in next version.

**Comment by reme3d2y** [comment]
if you have any problems, let me know :)

**Comment by ladislas14** [comment]
I will let you know ;) 


In the meantime, thank you very much for your responsiveness !
